Repository Nexters/zzanji-server, pull requests merged in 2023-08, with the labels that each got.

#45 feat: 유저 개인별 알람 시간 설정 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/notification.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nexters/jjanji/domain/notification/application/NotificationService.java
  src/main/java/com/nexters/jjanji/domain/notification/domain/NotificationInfo.java
  src/main/java/com/nexters/jjanji/domain/notification/domain/repository/NotificationInfoRepository.java
  src/main/java/com/nexters/jjanji/domain/notification/dto/request/ConfigNotificationRequestDto.java
  src/main/java/com/nexters/jjanji/domain/notification/presentation/NotificationController.java
  src/main/java/com/nexters/jjanji/domain/notification/specification/OperatingSystem.java
  src/main/java/com/nexters/jjanji/global/auth/DeviceIdAuthInterceptor.java
  src/main/java/com/nexters/jjanji/global/auth/MemberContext.java
  src/test/java/com/nexters/jjanji/domain/notification/presentation/NotificationControllerTest.java
Labels: feature

#51 feat: 참여 내역 삭제 api 구현
  src/docs/asciidoc/challenge.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/ChallengeService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeController.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationRepositoryTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeControllerTest.java
Labels: feature

#50 refactor: 강제 업데이트용 버전 체크 api 로 분리
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/nexters/jjanji/global/auth/AuthController.java
  src/main/java/com/nexters/jjanji/global/filter/ServiceVersionCheckFilter.java
  src/test/java/com/nexters/jjanji/global/auth/AuthControllerTest.java
Labels: refactor

#48 feat: 스케줄링 기반 FCM 푸시 알람 구현
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/com/nexters/jjanji/domain/notification/application/NotificationService.java
  src/main/java/com/nexters/jjanji/domain/notification/domain/repository/NotificationInfoRepository.java
  src/main/java/com/nexters/jjanji/domain/notification/presentation/NotificationController.java
  src/main/java/com/nexters/jjanji/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/nexters/jjanji/global/config/ScheduleConfig.java
  src/main/java/com/nexters/jjanji/infra/pushnotification/FCMCloudMessageClient.java
  src/main/java/com/nexters/jjanji/infra/pushnotification/FCMPushNotificationClient.java
  src/main/java/com/nexters/jjanji/infra/pushnotification/PushMessage.java
  src/main/java/com/nexters/jjanji/infra/pushnotification/PushNotificationClient.java
  src/main/java/com/nexters/jjanji/infra/pushnotification/dto/RequestPushDto.java
  src/main/resources/application.yml
Labels: documentation, feature

#59 [fix] json 라이브러리 추가
  build.gradle
  gradlew
Labels: bug
