Repository Nexters/zzanji-server, pull requests merged in 2023-07, with the labels that each got.

#2 feat: device id를 활용한 임시 로그인 구현
  build.gradle
  src/main/java/com/nexters/jjanji/common/auth/DeviceIdAuthInterceptor.java
  src/main/java/com/nexters/jjanji/common/auth/MemberContext.java
  src/main/java/com/nexters/jjanji/common/config/InterceptorConfig.java
  src/main/java/com/nexters/jjanji/member/api/MemberController.java
  src/main/java/com/nexters/jjanji/member/domain/Member.java
  src/main/java/com/nexters/jjanji/member/domain/MemberRepository.java
  src/main/java/com/nexters/jjanji/member/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#9 docs: spring rest docs 문서화 설정
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/nexters/jjanji/member/api/MemberController.java
  src/main/java/com/nexters/jjanji/member/dto/TestDto.java
  src/test/java/com/nexters/jjanji/docs/RestDocs.java
  src/test/java/com/nexters/jjanji/member/api/MemberControllerTest.java
Labels: documentation

#5 feat: 서비스 기본 도메인 설계
  src/main/java/com/nexters/jjanji/challenge/domain/Challenge.java
  src/main/java/com/nexters/jjanji/challenge/domain/Participation.java
  src/main/java/com/nexters/jjanji/challenge/domain/Plan.java
  src/main/java/com/nexters/jjanji/challenge/specification/PlanCategory.java
  src/main/java/com/nexters/jjanji/common/domain/BaseTime.java
  src/main/java/com/nexters/jjanji/member/domain/Member.java
Labels: feature

#6 feat: 월요일 00시에 다음주의 챌린지가 생성되는 스케줄러 개발
  src/main/java/com/nexters/jjanji/challenge/domain/Challenge.java
  src/main/java/com/nexters/jjanji/challenge/repository/ChallengeRepository.java
  src/main/java/com/nexters/jjanji/challenge/scheduler/ChallengeScheduler.java
  src/main/java/com/nexters/jjanji/challenge/service/ChallengeService.java
  src/test/java/com/nexters/jjanji/challenge/scheduler/ChallengeSchedulerTest.java
  src/test/java/com/nexters/jjanji/challenge/service/ChallengeServiceTest.java
Labels: feature

#13 feat: 다음주차 챌린지 참가 요청 api 구현
  .gitignore
  build.gradle
  src/docs/asciidoc/challenge.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/ChallengeService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Participation.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/request/ParticipateRequestDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nexters/jjanji/global/auth/DeviceIdAuthInterceptor.java
  src/test/java/com/nexters/jjanji/challenge/application/ChallengeServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/ChallengeServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeRepositoryTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeControllerTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/MemberControllerTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/scheduler/ChallengeSchedulerTest.java
Labels: feature

#19 feat: GitAction CI Workflow 추가
  .github/workflows/CI.yml
Labels: documentation

#21 feat: GitAction CD Workflow 추가
  .github/workflows/CD.yml
Labels: documentation

#22 feat: Docker 파일 추가 및 GitAction CI/CD WorkFlow 파일 수정
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile-dev
  Dockerfile-prod
Labels: documentation

#26 feat: 카테고리 별 지출 내역 등록 API 구현
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/spending.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/SpendingHistory.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/request/SpendingSaveDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryController.java
  src/main/java/com/nexters/jjanji/global/exception/BaseException.java
  src/main/java/com/nexters/jjanji/global/exception/NotExistPlanException.java
  src/main/java/com/nexters/jjanji/global/exception/exhandler/BaseExControllerAdvice.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryControllerTest.java
Labels: documentation, feature

#29 feat: 챌린지 참여 내역 조회 api 구현
  src/docs/asciidoc/challenge.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/ChallengeService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Challenge.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Participation.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Plan.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeDao.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationDao.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/PlanRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/PrevAndNextPostVO.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/response/ParticipationResponseDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/response/PlanResponseDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nexters/jjanji/domain/challenge/scheduler/ChallengeScheduler.java
  src/main/java/com/nexters/jjanji/domain/challenge/specification/ChallengeState.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/ChallengeServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationDaoTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/ChallengeControllerTest.java
Labels: feature

#28 feat: 카테고리 별 지출 내역 리스트 조회 API 구현
  src/docs/asciidoc/spending.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/SpendingHistoryRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/query/SpendingHistoryQueryRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/query/SpendingHistoryQueryRepositoryImpl.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/response/SpendingDetail.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/response/SpendingDetailResponse.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryController.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/query/SpendingHistoryCustomRepositoryImplTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryControllerTest.java
Labels: documentation, feature

#34 refactor: exception handler 리팩토링
  src/main/java/com/nexters/jjanji/domain/challenge/application/ChallengeService.java
  src/main/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryService.java
  src/main/java/com/nexters/jjanji/global/exception/AlreadyParticipateException.java
  src/main/java/com/nexters/jjanji/global/exception/BaseException.java
  src/main/java/com/nexters/jjanji/global/exception/NotExistPlanException.java
  src/main/java/com/nexters/jjanji/global/exception/NotParticipateException.java
  src/main/java/com/nexters/jjanji/global/exception/exhandler/BaseExControllerAdvice.java
  src/main/java/com/nexters/jjanji/global/exception/exhandler/ExceptionResponse.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/ChallengeServiceTest.java
Labels: refactor

#37 feat: 확정된 소비 카테고리 추가
  src/docs/asciidoc/challenge.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/specification/PlanCategory.java
Labels: documentation, feature

#35 feat: 카테고리 별 지출 내역 수정 API 구현
  src/docs/asciidoc/spending.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Challenge.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Plan.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/SpendingHistory.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/request/SpendingEditDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryController.java
  src/main/java/com/nexters/jjanji/global/exception/NotExistPlanException.java
  src/main/java/com/nexters/jjanji/global/exception/PlanChallengeNotFoundException.java
  src/main/java/com/nexters/jjanji/global/exception/PlanNotFoundException.java
  src/main/java/com/nexters/jjanji/global/exception/SpendingNotFoundExcpetion.java
  src/main/java/com/nexters/jjanji/global/exception/SpendingPeriodInvalidException.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeRepositoryTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryControllerTest.java
Labels: documentation, feature

#39 feat: 소비내역 등록 시 누락 기능 추가
  src/docs/asciidoc/spending.adoc
  src/main/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryService.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/request/SpendingEditDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/dto/request/SpendingSaveDto.java
  src/main/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryController.java
  src/main/java/com/nexters/jjanji/global/exception/SpendingPeriodInvalidException.java
  src/main/java/com/nexters/jjanji/global/exception/exhandler/BaseExControllerAdvice.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/SpendingHistoryServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/presentation/SpendingHistoryControllerTest.java
Labels: documentation, feature

#40 feat: 이전 챌린지 참가 내역으로 다음 챌린지에 참가하는 배치 로직 추가
  src/main/java/com/nexters/jjanji/domain/challenge/application/ChallengeService.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Challenge.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ChallengeDao.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/repository/PlanRepository.java
  src/main/java/com/nexters/jjanji/domain/challenge/scheduler/ChallengeScheduler.java
  src/test/java/com/nexters/jjanji/domain/challenge/application/ChallengeServiceTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/ParticipationRepositoryTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/domain/repository/PlanRepositoryTest.java
  src/test/java/com/nexters/jjanji/domain/challenge/scheduler/ChallengeSchedulerTest.java
Labels: feature, refactor

#42 feat: 0.5버전 더미데이터 추가
  src/main/java/com/nexters/jjanji/DummyConfig.java
  src/main/java/com/nexters/jjanji/DummyDataInit.java
  src/main/java/com/nexters/jjanji/domain/challenge/domain/Plan.java
Labels: feature
